version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - todo-net
    volumes:
      - todo:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  todo:

networks:
  todo-net:
